name: docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: pip install mkdocs==1.1.2 mkdocs-material==7.1.5 mkdocstrings==0.15.1 fierpy
      - run: mkdocs gh-deploy --force